# Generated by Django 5.1.4 on 2025-01-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
